package GUI.GUI_BoxLook_New_25072020.Controller.II_MethodsController;

import GUI.GUI_BoxLook_New_25072020.MethodLibrary.MethodsLibrary.III_MajorMethods_Shapelet.MajorMethods_Shapelet;
import GUI.GUI_BoxLook_New_25072020.MethodLibrary.MethodsLibrary.II_MajorMethods_TImeseries.MajorMethods_Timeseries;
import GUI.GUI_BoxLook_New_25072020.MethodLibrary.MethodsLibrary.IV_SetInfo_Charts.SetInfo_Charts;
import GUI.GUI_BoxLook_New_25072020.MethodLibrary.MethodsLibrary.I_ComponentsAddListners.ComponentsAddListners;
import GUI.GUI_BoxLook_New_25072020.MethodLibrary.MethodsLibrary.VII_SortData.SortData;
import GUI.GUI_BoxLook_New_25072020.MethodLibrary.MethodsLibrary.VI_Clear_TracesAndCharts.Clear_TracesAndCharts;
import GUI.GUI_BoxLook_New_25072020.MethodLibrary.MethodsLibrary.V_SetScaleAndPosition_AllCharts.SetScaleAndPosition_AllCharts;

public abstract class MethodsController_declare_abstract{
    protected ComponentsAddListners aComponentsAddListners;
    protected MajorMethods_Timeseries aMajorMethods_Timeseries;
    protected MajorMethods_Shapelet aMajorMethods_Shapelet;
    protected SetInfo_Charts aSetInfo_Charts;
    protected SetScaleAndPosition_AllCharts aSetScaleAndPosition_AllCharts;
    protected Clear_TracesAndCharts aClear_TracesAndCharts;
    protected SortData aSortData;
}
